var DCAgentPaymentConfig = function() {};
var DCAgentConfig = function() {};

var _classCallCheck=function(l,k){if(!(l instanceof k))throw new TypeError("Cannot call a class as a function");},_createClass=function(){function l(k,l){for(var A=0;A<l.length;A++){var x=l[A];x.enumerable=x.enumerable||!1;x.configurable=!0;"value"in x&&(x.writable=!0);Object.defineProperty(k,x.key,x)}}return function(k,G,A){G&&l(k.prototype,G);A&&l(k,A);return k}}();
(function(l,k){"object"===typeof exports&&"undefined"!==typeof module?k(exports):"function"===typeof define&&define.amd?define("DCAgent",["exports"],k):k(l.DCAgent={})})(this,function(l){function k(){}function G(b){return"function"===typeof b}function A(b){var a,c;a=Date.now();c="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var c;c=(a+16*Math.random())%16|0;a=Math.floor(a/16);return"x"===b?c.toString(16):(c&7|8).toString(16)});return(b||"")+c.replace(/-/g,"").toUpperCase()}function x(b){var a,
c;for(a in b)c=b[a],b[a]=c;(2<=arguments.length?[].slice.call(arguments,1):[]).forEach(function(e){var h;h=[];for(a in e)c=e[a],h.push(b[a]=c);return h});return b}function n(b,a,c){if(G(b))try{return b.apply(a,c)}catch(e){p("attemp error for "+b.toString(),e.stack)}}function p(b,a){console.log("#DCAgent: "+b);a&&console.log(a)}function Sa(b){try{return b.setItem(".","."),b.removeItem("."),!0}catch(a){return!1}}function ia(b,a,c){if(!b||b&&b.length>=c)return b;c=Math.ceil(c-b.length)/a.length;c=void 0===
c?0:c;for(var e="",h=0;h<c;h+=1)e+=a;return b+e}function Ta(b,a,c){return function(){Array.isArray(a)||(a=[a]);Array.isArray(c)||(c=[c]);var e,h;for(e=0;e<a.length;e+=1)if(h=a[e],!1===n(h,this,arguments))return;var g=n(b,this,arguments);if(!1===g)return!1;for(e=0;e<c.length;e+=1)h=c[e],n(h,this,arguments);return g}}function Ua(b){return b?(b=b.match(/^(https?\:)\/\/(([^:\/?#]*)(?:\:([0-9]+))?)(\/[^?#]*)(\?[^#]*|)(#.*|)$/))&&b[3]:""}function m(b,a,c){a=void 0===a?0:a;1E21<=b&&(b=9.527E19);return f.parseInt(b,
void 0===c?10:c)||a}function W(b){return"undefined"!==typeof f[b]}function J(b,a){b=u(b);r.setItem(b,a);ja.set(b,a,3650);return a}function O(b){b=u(b);return r.getItem(b)||ja.get(b)}function u(b){if(X||Y===b)return b;d.appId||p("appid should not be empty when you are in native env");return d.appId+"."+b}function Va(b){var a=v.hash,c="!"+b,e="";if(a){var h=/![0-9A-Z]{32,128}/gi;(a=a.match(h))?(a=a[0].slice(1),b===a||O(ka)||(e=a),v.href=v.href.replace(h,c)):v.href+=c}else v.href+="#"+c;J(ka,e);return e}
function la(b){b=u(b);try{var a=JSON.parse(r.getItem(b));return Array.isArray(a)?a:[]}catch(c){return r.removeItem(b),[]}}function Wa(b,a){a=u(a);var c=la(a);Array.isArray(b)?b.forEach(function(b){return c.push(b)}):c.push(b);r.setItem(a,JSON.stringify(c))}function Xa(){r.removeItem(u(H));r.removeItem(u(K))}function Ya(){f.addEventListener&&f.addEventListener("error",function(b){n(function(){if(B.isReportAllowed(b.filename)){B.count+=1;var a={};["colno","filename","lineno","message"].forEach(function(c){return a[c]=
b[c]||"1"});var c=b.error||{};a.stack=encodeURIComponent(c.stack||c.stacktrace||"");a.type=c.name||"Error";a.timestamp=parseInt(b.timeStamp/1E3);if(G(d.getErrorScene)&&(c=n(d.getErrorScene,c,[b]))){if(c&&"[object Object]"===ma.call(c)){var e="",h;for(h in c)e+="\t"+h+"="+c[h]+"\n";c=e}else c=String(c);a.stack+="\n\nError scene:\n"+encodeURIComponent(c)}F.updateStorageByKey(a,K)}})},!1)}function Za(){if(!C){C={ver:na};oa.split(",").forEach(function(b){C[b]=d.hasOwnProperty(b)?d[b]:""});for(var b in pa)C[b]=
d[b]||pa[b],C[b]||0===C[b]||(C[b]="")}return C}function $a(){var b=Za();b.accountId=d.accountId||d.uid;(qa+","+Z).split(",").forEach(function(a){b[a]=d.hasOwnProperty(a)?d[a]:""});return b}function ra(b){var a=sa();a.timeout=ta;a.open("POST",b.url,!0);a.setRequestHeader("Content-Type","text/plain; charset=UTF-8");var c=Date.now();a.onreadystatechange=function(){if(4===this.readyState){var a=200<=this.status&&300>this.status,h=Date.now()-c;n(a?b.success:b.error,this,[this,h]);n(b.complete,this,[this,
h]);this.ontimeout=this.onreadystatechange=null}};a.ontimeout=function(){var a=Date.now()-c;n(b.error,this,[this,a,!0]);n(b.complete,this,[this,a]);this.ontimeout=this.onreadystatechange=null};a.send(JSON.stringify(b.data))}function ab(b){var a=new egret.URLLoader,c=Date.now();a.addEventListener(egret.Event.COMPLETE,function(a){var e=Date.now()-c;a=a.target;n("success"===a.data?b.success:b.error,a,[a,e,e>=ta]);n(b.complete,a,[a,e])});var e=new egret.URLRequest(b.url);e.method=egret.URLRequestMethod.POST;
e.data=JSON.stringify(b.data);a.load(e)}function ua(b,a){if(b.data){b.data.errorInfoList&&b.data.errorInfoList.length>B.max&&(p("sending too many errors, only "+B.max+" allowed"),b.data.errorInfoList=b.data.errorInfoList.slice(0,B.max));var c=x({headerInfo:$a()},b.data);bb({url:cb+"//"+a,data:c,success:function(a,c){w.succ=1;w.fail=0;w.total=c;n(b.success,a,[a,c])},error:function(a,c,d){w.succ=0;w.fail+=1;w.total+=c;$+=1;n(b.error,a,[a,c,d]);d&&p("report timeout, network infomation",w)},complete:function(a,
c){aa+=1;F.updateStorageByKey({eventId:db,eventMap:w},H);n(b.complete,a,[a,c])}});p("report data:",c)}}function eb(){if(P)return P;ba+=1;if(!(4<ba)){var b={egret:"egret",layabox:"layabox",cocos:"cc.game",impact:"ig",phaser:"Phaser",pixi:"PIXI",create:"createjs",three:"THREE",gameMaker:"asset_get_type",playCanvas:"pc.fw",turbulenz:"TurbulenzEngine",quintus:"Quintus",melon:"me.game",lychee:"lychee",wade:"wade.addSceneObject",crafty:"Crafty",lime:"lime.Scene",enchant:"enchant",isogenic:"IgeEngine",gameclosure:"GC.Application",
panda:"game.Scene",kiwi:"Kiwi",jaws:"jaws",sirius2d:"ss2d",collie:"collie",physics:"Physics",stage:"Stage.Anim",babylon:"BABYLON"},a;for(a in b){var c=b[a];if(-1<c.indexOf(".")){var c=c.split("."),e=f[c[0]];if(e&&e[c[1]])return P=a}else if(f[c])return P=a}}}function va(b,a,c,e){var h=parseInt(Date.now()/1E3)-d.loginTime||1;if(h>=fb||0>=h)p("illegal online time: "+h);else{var g={data:{onlineInfo:{loginTime:d.loginTime,onlineTime:h,extendMap:{from:d.from,engine:eb()||"",app:d.app}},eventInfoList:b||
[],errorInfoList:a||[]},success:e};c&&(g.data.userInfo=c);b=F.getStorageByKey(H);a=F.getStorageByKey(K);if(b.length||a.length)F.clear(),g.data.eventInfoList=g.data.eventInfoList.concat(b),g.data.errorInfoList=g.data.errorInfoList.concat(a),g.error=function(){p("report failed, restoring data to localStorage");F.updateStorageByKey(g.data.eventInfoList,H);F.updateStorageByKey(g.data.errorInfoList,K);n(e,0,arguments)};ua(g,wa)}}function xa(b){ya&&q[ya]||va(0,0,0,b)}function gb(b,a){this.status="constructed";
this.run=function(){Q(this.timer);this.status="running";n(b);var c=this;this.timer=R(function(){return c.run()},a)};this.stop=function(){this.status="stopped";Q(this.timer)}}function hb(b){if(d.uid){var a=ia(d.uid,za,Aa);b!==a&&(d.uid=a,p("do u know you are updating device id?"),J(ca,parseInt(Date.now()/1E3)),b=d.uid)}if(!b){var c;try{if(s.realBrowser)c=(new ib({canvas:!0,screen_resolution:!0,ie_activex:!0})).get().toString();else if(s.engine.layabox){var e=layabox.getDeviceInfo()||{};c=(c=e.mac||
e.idfa)&&c.replace(/[-_:=\s]+/g,"").toUpperCase()}}catch(h){c=null}c=ia(c,za,Aa);c||(c=Date.now().toString(36).toUpperCase(),c=A(s.engine.egret?jb+c:s.engine.layabox?kb+c:s.engine.cocos?lb+c:mb+c));b=c}c=b;J(Y,c);return c}function nb(b){var a=O(Y),c=a?0:1,a=hb(a);d.uid=a;d.accountId=a;d.interval=1E3*Math.max(Ba,parseFloat(b.interval||Ba));d.virus&&s.realBrowser&&(d.parentId=Va(a));d.errorReport&&(B.excludes=Array.isArray(b.excludes)?B.excludes.concat(b.excludes):[],Ya());d.timer=new gb(xa,d.interval);
d.timer.status="running";d.loginTime=parseInt(Date.now()/1E3);d.initTime=d.loginTime;a=O(ca);a||(a=d.loginTime,J(ca,a));d.createTime=parseInt(a);c=c?{actTime:a,regTime:a,parentId:d.parentId}:null;va([{eventId:ob,eventMap:{page:encodeURIComponent(s.realBrowser?v.pathname+v.search:"!")}}],0,c);R(function(){return d.timer.run()},d.interval);pb(function(){var a=parseInt(Date.now()/1E3);J(Ca,a)});D.setUserOptions(b);D.inited=!0}function Da(b){b=u(b);try{var a=JSON.parse(r.getItem(b));return Array.isArray(a)?
a:[]}catch(c){return r.removeItem(b),[]}}function qb(b,a){a=u(a);var c=Da(a);Array.isArray(b)?b.forEach(function(a){return c.push(a)}):c.push(b);r.setItem(a,JSON.stringify(c))}function rb(){r.removeItem(u(H));r.removeItem(u(K))}function t(b,a){if(!b)return p("invoke failed, missing eventId"),!1;2<arguments.length&&(a=arguments[2]);var c={};if(a&&"[object Object]"===ma.call(a))for(var e in a)c[e.replace("%","_")]="number"===typeof a[e]?a[e]:encodeURIComponent(a[e]);sb.updateStorageByKey({eventId:b,
eventMap:c},H)}function Ea(b){return function(){var a=D.getLoginStatus();if(0===a)return p("DCAgent.login needed"),!1;if(1===a){var c=[b];[].forEach.call(arguments,function(a){return c.push(a)});da.push(c);return!1}}}function tb(){da.forEach(function(b){return S[b.shift()].apply(0,b)});da.length=0}function Fa(){Q(Ga);var b=d.timer;b.stop();Ga=R(function(){b.run()},ub)}var Ha,Ia=0,D={getUserOptions:function(){return Ha},setUserOptions:function(b){Ha=JSON.stringify(b)},setLoginStatus:function(b){Ia=
b},getLoginStatus:function(){return Ia}},ea=(0,eval)("this"),f=ea||{},q=ea.document||{},v=ea.location||{},ma=Object.prototype.toString,ya="hidden"in q?"hidden":"webkitHidden"in q?"webkitHidden":"mozHidden"in q?"mozHidden":"msHidden"in q?"msHidden":null,d={age:0,gender:0,roleLevel:0,netType:3},s={get engine(){return I},get localStorage(){return vb},get realBrowser(){return X},get cookie(){return wb}},Ja;if("function"===typeof q.createElement){var T=q.createElement("div");if(T&&"function"===typeof T.querySelector){T.innerHTML=
"<i></i>";var Ka=T.querySelector("i");Ja=!!Ka&&"I"===Ka.tagName}}var I={egret:W("egret"),layabox:W("layabox"),cocos:W("cc")},vb=!!f.localStorage||I.egret||I.cocos,X=Ja,wb=X&&"cookie"in q,ca="dcagent_create_time",jb="EGRET",kb="LAYA",lb="COCOS",mb="UE",ka="dcagent_parent_id",H="dcagent_client_events",K="dcagent_client_errors",Y="dcagent_client_id",Ca="dc_p_lo",wa="rd.gdatacube.net/dc/hh5/sync",za="0A",Aa=32,db="DE_EVENT_OSS",ta=3E4,fb=172800,Ba=20,oa="appId,appVersion,brand,channel,customDeviceId,idfa,imei,lonLat,mac,netType,operator,osVersion,platform,simCardOp,uid",
qa="accountId,accountType,age,gender,gameServer",Z="roleId,roleRace,roleClass,roleLevel",ob="DE_EVENT_PV",ub=5E3,r;r=s.engine.egret?egret.localStorage:s.engine.cocos?cc.sys.localStorage:s.localStorage?f.localStorage:{getItem:k,setItem:k,removeItem:k};var La,ja=La=s.cookie?{get:function(b){return(b=q.cookie.match(new RegExp("(^|)\\s*"+b+"=([^\\s]*)")))&&3<=b.length?decodeURIComponent(b[2]):null},set:function(b,a,c,e,d,g){var U;c&&(U=new Date,U.setTime(U.getTime()+864E5*c));c=c?" expires="+U.toGMTString():
"";d=" path="+(d||"/");e=e?" domain="+e:"";g=g?" secure":"";q.cookie=b+"="+encodeURIComponent(a)+c+d+e+g},remove:function(b,a,c){La.set(b,"",-1,a,c)}}:{get:k,set:k,remove:k},V={max:100,count:0,excludes:[],isReportAllowed:function(b){if(V.count<V.max)return V.excludes.every(function(a){return-1===b.indexOf(a)})}},B=V,y=f.screen,z=f.navigator,ib=function(){function b(a){_classCallCheck(this,b);var c,e;c=Array.prototype.forEach;e=Array.prototype.map;this.each=function(a,b,e){if(null!==a)if(c&&a.forEach===
c)a.forEach(b,e);else if(a.length===+a.length)for(var d=0,f=a.length;d<f&&b.call(e,a[d],d,a)!=={};d++);else for(d in a)if(a.hasOwnProperty(d)&&b.call(e,a[d],d,a)==={})break};this.map=function(a,b,c){var d=[];if(null==a)return d;if(e&&a.map===e)return a.map(b,c);this.each(a,function(a,e,h){d[d.length]=b.call(c,a,e,h)});return d};"object"==typeof a?(this.hasher=a.hasher,this.screen_resolution=a.screen_resolution,this.screen_orientation=a.screen_orientation,this.canvas=a.canvas,this.ie_activex=a.ie_activex):
"function"==typeof a&&(this.hasher=a)}_createClass(b,[{key:"get",value:function(){var a=[];a.push(z.userAgent);a.push(z.language);a.push(y.colorDepth);if(this.screen_resolution){var b=this.getScreenResolution();"undefined"!==typeof b&&a.push(b.join("x"))}a.push((new Date).getTimezoneOffset());a.push(this.hasSessionStorage());a.push(this.hasLocalStorage());a.push(!!f.indexedDB);q.body?a.push(typeof q.body.addBehavior):a.push("undefined");a.push(typeof f.openDatabase);a.push(z.cpuClass);a.push(z.platform);
a.push(z.doNotTrack);a.push(this.getPluginsString());this.canvas&&this.isCanvasSupported()&&a.push(this.getCanvasFingerprint());return this.hasher?this.hasher(a.join("###"),31):this.murmurhash3_32_gc(a.join("###"),31)}},{key:"murmurhash3_32_gc",value:function(a,b){var d,h,g,f,k;d=a.length&3;h=a.length-d;g=b;for(k=0;k<h;)f=a.charCodeAt(k)&255|(a.charCodeAt(++k)&255)<<8|(a.charCodeAt(++k)&255)<<16|(a.charCodeAt(++k)&255)<<24,++k,f=3432918353*(f&65535)+((3432918353*(f>>>16)&65535)<<16)&4294967295,f=
f<<15|f>>>17,f=461845907*(f&65535)+((461845907*(f>>>16)&65535)<<16)&4294967295,g^=f,g=g<<13|g>>>19,g=5*(g&65535)+((5*(g>>>16)&65535)<<16)&4294967295,g=(g&65535)+27492+(((g>>>16)+58964&65535)<<16);f=0;switch(d){case 3:a.charCodeAt(k+2);break;case 2:a.charCodeAt(k+1);break;case 1:f^=a.charCodeAt(k)&255,f=3432918353*(f&65535)+((3432918353*(f>>>16)&65535)<<16)&4294967295,f=f<<15|f>>>17,g^=461845907*(f&65535)+((461845907*(f>>>16)&65535)<<16)&4294967295}g^=a.length;g^=g>>>16;g=2246822507*(g&65535)+((2246822507*
(g>>>16)&65535)<<16)&4294967295;g^=g>>>13;g=3266489909*(g&65535)+((3266489909*(g>>>16)&65535)<<16)&4294967295;return(g^g>>>16)>>>0}},{key:"hasLocalStorage",value:function(){try{return!!f.localStorage}catch(a){return!0}}},{key:"hasSessionStorage",value:function(){try{return!!f.sessionStorage}catch(a){return!0}}},{key:"isCanvasSupported",value:function(){var a=q.createElement("canvas");return!(!a.getContext||!a.getContext("2d"))}},{key:"isIE",value:function(){return"Microsoft Internet Explorer"===z.appName||
"Netscape"===z.appName&&/Trident/.test(z.userAgent)?!0:!1}},{key:"getPluginsString",value:function(){return this.isIE()&&this.ie_activex?this.getIEPluginsString():this.getRegularPluginsString()}},{key:"getRegularPluginsString",value:function(){return this.map(z.plugins,function(a){var b=this.map(a,function(a){return[a.type,a.suffixes].join("~")}).join(",");return[a.name,a.description,b].join("::")},this).join(";")}},{key:"getIEPluginsString",value:function(){return f.ActiveXObject?this.map("ShockwaveFlash.ShockwaveFlash;AcroPDF.PDF;PDF.PdfCtrl;QuickTime.QuickTime;rmocx.RealPlayer G2 Control;rmocx.RealPlayer G2 Control.1;RealPlayer.RealPlayer(tm) ActiveX Control (32-bit);RealVideo.RealVideo(tm) ActiveX Control (32-bit);RealPlayer;SWCtl.SWCtl;WMPlayer.OCX;AgControl.AgControl;Skype.Detection".split(";"),
function(a){try{return new f.ActiveXObject(a),a}catch(b){return null}}).join(";"):""}},{key:"getScreenResolution",value:function(){return this.screen_orientation?y.height>y.width?[y.height,y.width]:[y.width,y.height]:[y.height,y.width]}},{key:"getCanvasFingerprint",value:function(){var a=q.createElement("canvas"),b=a.getContext("2d");b.textBaseline="top";b.font="14px 'Arial'";b.textBaseline="alphabetic";b.fillStyle="#f60";b.fillRect(125,1,62,20);b.fillStyle="#069";b.fillText("http://www.dataeye.com/",
2,15);b.fillStyle="rgba(102, 204, 0, 0.7)";b.fillText("http://www.dataeye.com/",4,17);return a.toDataURL()}}]);return b}(),F={get getStorageByKey(){return la},get updateStorageByKey(){return Wa},get clear(){return Xa}},na=20;l.version=na;var pa={get resolution(){return L},get brand(){return Ma},get osVersion(){return Na},get platform(){return M}},fa=f.screen||{},L=fa.width&&fa.width+"*"+fa.height,Ma,Na,M=0;if(!f.navigator||!f.navigator.userAgent){var Oa=["ios","android"];if(I.layabox){var N=layabox.getDeviceInfo()||
{},L=N.resolution||"0*0";Ma=N.phonemodel;M=Oa.indexOf(N.os.toLowerCase());Na=(N.os+" "+N.osversion).toLowerCase()}else if(I.cocos)var Pa=cc.view.getViewPortRect()||{},L=Pa.width+"*"+Pa.height,M=Oa.indexOf(cc.sys.os.toLowerCase());-1===[0,1,2,3].indexOf(M)&&(M=0)}L||(L="0*0");var C,w={succ:0,fail:0,total:0},sa=function(){return new f.XMLHttpRequest},bb=function(){if(f.XMLHttpRequest)return ra;if(s.engine.cocos)return sa=function(){return cc.loader.getXMLHttpRequest()},ra;if(s.engine.egret)return ab;
p("XMLHttpRequest not found");return k}(),aa=0,$=0,cb="https:"===v.protocol?"https:":"http:",P,ba=0,R=f.setTimeout,Q=f.clearTimeout;I.egret&&(R=function(b,a){egret.setTimeout(b,f,a)},Q=function(b){egret.clearTimeout(b)});var pb=function(b){if(f.addEventListener){var a;a:{a=["pagehide","beforeunload","unload"];for(var c=0;c<a.length;c+=1)if("on"+a[c]in f){a=a[c];break a}a=void 0}a&&f.addEventListener(a,b)}};l.init=function(b){Sa(r)?D.inited||(b=b||{},b.appId?(["errorReport","virus"].forEach(function(a){return d[a]=
b.hasOwnProperty(a)?!!b[a]:!0}),d.app=b.appName||"",d.from=b.from||Ua(q.referrer),d.getErrorScene=b.getErrorScene,oa.split(",").forEach(function(a){b.hasOwnProperty(a)&&(d[a]=b[a])}),nb(b)):p("init failed, missing appId")):s.localStorage?p("localstorage qouta error, private mode?"):p("localstorage is not supported.")};var sb={get getStorageByKey(){return Da},get updateStorageByKey(){return qb},get clear(){return rb}},xb={get initBasedAPI(){return ga},get loginBasedAPI(){return S},get cacheBeforeLogin(){return Ea},
get clearLoginInvokeList(){return tb},get asap(){return Fa}},ga={login:function(b){b?d.accountId!==b&&(1===D.getLoginStatus()?p("cancel login, current login is not ready"):(d.timer.stop(),D.setLoginStatus(1),xa(function(){D.setLoginStatus(2);(qa+","+Z).split(",").forEach(function(a){return delete d[a]});d.age=0;d.gender=0;d.roleLevel=0;d.loginTime=parseInt(Date.now()/1E3);d.accountId=b;xb.clearLoginInvokeList();d.timer.run()}))):p("account is empty")},onEvent:t},S={onCoinGet:function(b,a,c,d){t("DE_EVENT_COIN_ACTION",
{actionType:"coinGet",coinType:c,balanceNum:m(a),coinNum:m(b),reason:d})},onCoinUse:function(b,a,c,d){t("DE_EVENT_COIN_ACTION",{actionType:"coinUse",coinType:c,balanceNum:m(a),coinNum:m(b),reason:d})},onItemBuy:function(b,a,c,d,f){t("DE_EVENT_ITEM_ACTION",{actionType:"itemBuy",itemId:b,itemNum:m(a),coinType:c,coinNum:m(d),missonID:f})},onItemProduce:function(b,a,c,d){t("DE_EVENT_ITEM_ACTION",{actionType:"itemGet",itemId:b,itemNum:m(a),missonID:c,reason:d})},onItemUse:function(b,a,c,d){t("DE_EVENT_ITEM_ACTION",
{actionType:"itemUse",itemId:b,itemNum:parseInt(a),reason:d,missonID:c})},onLevelUp:function(b,a,c){a=m(a);d.roleLevel=a;t("DE_EVENT_LEVELUP",{startLevel:m(b),endLevel:a,duration:m(c)})},onMissionFinished:function(b,a){t("DE_EVENT_GUANKA_ACTION",{actionType:"guankaFinish",guankaId:b,duration:m(a)})},onMissionUnfinished:function(b,a){t("DE_EVENT_GUANKA_ACTION",{actionType:"guankaUnfinish",guankaId:b,duration:m(a)})},onPayment:function(b){b&&b.hasOwnProperty("amount")&&ua({data:{paymentInfo:{currencyAmount:parseFloat(b.amount,
10)||0,currencyType:b.currencyType||"CNY",payType:String(b.payType||""),iapid:String(b.iapid||""),payTime:m(Date.now()/1E3),extendMap:{orderId:String(b.orderId||"")}}}},wa)},onTaskFinished:function(b,a){t("DE_EVENT_TASK_ACTION",{actionType:"taskFinish",taskId:b,elapsed:m(a)})},onTaskUnfinished:function(b,a){t("DE_EVENT_TASK_ACTION",{actionType:"taskUnfinish",taskId:b,elapsed:m(a)})},setAccountType:function(b){d.accountType=String(void 0===b?"":b)},setAge:function(b){b=m(b);d.age=0<b&&128>b?b:0},setGameServer:function(b){d.gameServer=
String(void 0===b?"":b)},setGender:function(b){d.gender=2===b?2:1},setRoleInfo:function(b,a,c,e){var f=arguments;Z.split(",").forEach(function(a,b){return d[a]=f[b]||""});d.roleLevel=m(e)||1}},da=[],Ga;l.player={get isNew(){return d.createTime===d.loginTime},get initTime(){return d.initTime},get createTime(){return d.createTime},get loginTime(){return d.loginTime},get lastLogoutTime(){return m(O(Ca))},get getReportCount(){return aa},get getReportFailedCount(){return $}};var yb=D.getUserOptions,E;
for(E in ga)l[E]=ga[E];for(E in S)l[E]=Ta(S[E],[Ea(E)],["onPayment"!==E&&Fa]);var Qa=f.DCAgentObject;if(Qa){var Ra=f[Qa];if(G(Ra)){var ha=Ra.cache;ha.length&&(ha.forEach(function(b){n(l[b[0]],l,[].slice.call(b,1,void 0))}),ha.length=0)}}l.__options=yb});

/**
 * DataEye SDK for HTML5 2.0
 *
 * 更多信息请前往 http://wiki.dataeye.com/h5/document/html5/guide.html
 *
 * Copyright@2013 DataEye
 */
var DCAgentGender;
(function (DCAgentGender) {
    DCAgentGender[DCAgentGender["male"] = 1] = "male";
    DCAgentGender[DCAgentGender["female"] = 2] = "female";
})(DCAgentGender || (DCAgentGender = {}));
;

